#\DeclareLyXModule{OpenU Formatting}
#\DeclareCategory{OpenUniversity}
#DescriptionBegin
#Includes commands and settings for the document layout. Author: Ehud Behar. Updated 2026-Feb-20
#DescriptionEnd
#Author: Ehud Behar

Format 66

Requires xcolor,amssymb,enumitem,graphicx

ClassOptions
  Other "fleqn,leqno,provide=*,bidi=default"
End

# Choose the engine that will process the .tex file when opened in TeXShop, TeXWorks or TeXstudio
AddToPreamble
% !TEX TS-program = lualatex
EndPreamble

AddToPreamble
\definecolor{DGray}{RGB}{149,149,149} % Dark Gray
\definecolor{LGray}{RGB}{216,216,216} % Light Gray
\definecolor{VDGray}{RGB}{110,110,110} % VeryDarkGray
EndPreamble

# Defone font sizes
AddToPreamble
% Define normal size to be 11.5pt
\def\normalsize{%
  \@setfontsize\normalsize{11.5}{17pt}%
  \abovedisplayskip 11.5pt plus 2.3pt minus 6.9pt
  \abovedisplayshortskip 0.0pt plus 3.45pt
  \belowdisplayskip 11.5pt plus 2.3pt minus 6.9pt
  \belowdisplayshortskip 6.9pt plus 3.45pt minus 3.45pt
  \let\@listi\@listI
}%
% Define small size to be 9.5pt
\def\small{%
  \@setfontsize\small{9.5}{14.04pt}%
  \abovedisplayskip 9.5pt plus 1.9pt minus 5.7pt
  \abovedisplayshortskip 0.0pt plus 2.85pt
  \belowdisplayskip 9.5pt plus 1.9pt minus 5.7pt
  \belowdisplayshortskip 5.7pt plus 2.85pt minus 2.85pt
  \def\@listi{%
    \leftmargin\leftmargini
    \topsep4.16391pt plus 2.08261pt minus 2.08261pt
    \parsep2.08261pt plus 1.04063pt minus 1.04063pt
    \itemsep\parsep
  }%
}%
% Define smallr font size; the 'r' stands for "reduced" or "relative". This font size is used only in the headers
\def\smallr{\@setfontsize\smallr{10pt}{14.782pt}}%
\def\Huge{\@setfontsize\Huge{30pt}{36pt}}%
\def\huge{\@setfontsize\huge{26.0975pt}{31.317pt}}%
\def\Large{\@setfontsize\Large{20.075pt}{22.0pt}}%
\def\large{\@setfontsize\large{17.063pt}{18.0pt}}%
EndPreamble

# fontspec and babel commands to select fonts
AddToPreamble
% Load fontspec package
\usepackage{fontspec}
\defaultfontfeatures{Scale=MatchUppercase, Ligatures=TeX}
% Glyph em-dash is not available in NarkisimMF, print it en-dash:
\catcode`—=\active \protected\def—{\char`\--}
% Use unicode-math package, so math fonts scales to 11.5pt font size
\usepackage[mathbf=sym]{unicode-math}
\setmathfont{Latin Modern Math} %to do: change this to cambria
% Make emphasized math also in bold:
\setmathfont{Latin Modern Math}[version=bold,FakeBold=3]
% Use Latin Modern Math for blackboard
\let\mathbb\relax
\DeclareMathAlphabet{\mathbb}{U}{msb}{m}{n}%

% add babel font commands to end of preamble
\usepackage{etoolbox}
\AtEndPreamble{%
\babelprovide[main,import=he,onchar=fonts ids]{hebrew}
% Main Hebrew font (rm family)
\babelfont[hebrew]{rm}[Script=Hebrew]{NarkisimMF}%
% Monospace Hebrew font (teletype, tt family)
\babelfont[hebrew]{tt}[Script=Hebrew]{Courier New}
% Sans serif Hebrew font (sf family)
\babelfont[hebrew]{sf}[Script=Hebrew]{Open Sans Hebrew}
% NarkisTamMF is used in the headers
\babelfont[hebrew]{narkistam}[Script=Hebrew,BoldFont=NarkisTamMF]{NarkisTamMF}
\babelfont[english]{rm}
    [Script=Latin,
     SizeFeatures={
         {Size={10-},Scale=0.86956},
         {Size={9-10},Scale=0.894736},
         {Size={8-9},Scale=1},
         {Size={-8}}
     },
     BoldFeatures={
         SizeFeatures={
             {Size={10-},Scale=0.86956},
             {Size={9-10},Scale=0.894736},
             {Size={8-9},Scale=1},
             {Size={-8}}
         }
     }]
    {Times New Roman}
\setlocalecaption{hebrew}{part}{כרך}
\setlocalecaption{hebrew}{chapter}{יחידה}
\setlocalecaption{hebrew}{contents}{תוכן עניינים ל\partname\ \thepart}
\renewcommand{\thepage}{\textdir TLT\csname @arabic\endcsname \c@page} %Reverse direction of page numbers
}
% change numbering of sections and subsections; change part counter with Hebrew numerals
\renewcommand{\thesection}{\arabic{section}.\thechapter}
\renewcommand{\thesubsection}{\arabic{subsection}.\thesection}
\renewcommand{\thepart}{\localecounter{letters}{part}}

% main matter page layout
\pagewidth=210mm \paperwidth=\pagewidth
\pageheight=297mm \paperheight=\pageheight
\textwidth=125mm
\textheight=220mm
\marginparsep=7mm
\marginparwidth=43mm
\evensidemargin=0cm
\headheight=22pt
\topmargin=0mm
\headsep=10mm
% apply a twosided layout in which margins are not swapped on alternate pages:
\oddsidemargin=\evensidemargin
\@twocolumnfalse
\@twosidetrue
% and marginal notes stay always on the same side:
\@mparswitchfalse
\@reversemarginfalse

% Define a new length `\headwidth` which is the total width of the headers:
\newlength\headwidth \headwidth=\dimexpr\textwidth+\marginparsep+\marginparwidth

% Redefine the plain page style (used on chapter opening pages)
\def\ps@plain{%
  \def\@oddhead{\vbox{\hsize=\headwidth \hfill{\narkistamfamily\large\thepage}\vskip1mm\hrule}\hskip\dimexpr-\marginparwidth-\marginparsep}
  \def\@evenhead{\vbox{\hsize=\headwidth \hfill\thepage\vskip1mm\hrule}\hskip\dimexpr-\marginparwidth-\marginparsep} % chapters headings are not supposed to appear on even pages; we define it just in case
}

% Redefine the headings page style (used on regular pages)
\def\ps@headings{%
  \def\@oddhead{\vbox{\hsize=\headwidth \hfill{\narkistamfamily\rightmark\hskip2mm\large\thepage}\vskip1mm\hrule}\hskip\dimexpr-\marginparwidth-\marginparsep}
  \def\@evenhead{\vbox{\hsize=\headwidth \narkistamfamily{\large\thepage}~\leftmark\vskip1mm\hrule}\hskip\dimexpr-\marginparwidth-\marginparsep}
}

% Customize chapter and section marks
\renewcommand{\chaptermark}[1]{%
  \markboth{\chaptername~\thechapter\hskip0.2cm #1}{}%
}
\renewcommand{\sectionmark}[1]{%
  \markright{{\textdir TLT\thesection}~#1}%
}
\pagestyle{headings}
EndPreamble

## Titles (chapter,section,subsec etc.) formatting
AddToPreamble
%% Titles (chapter,section,subsec etc.) formatting
% Part title
\def\@part[#1]#2{%
  \thispagestyle{empty}
  \refstepcounter{part}%
  \markboth{}{}%
%\AddToHookNext{shipout/background}{\put(\dimexpr .85\paperwidth-4.5cm,-200){\includegraphics[width=4.5cm]{logo.pdf}}}
  \vspace*{\fill}
    {\raggedright
     \interlinepenalty \@M
     \normalfont
     \ifnum \c@secnumdepth >-2\relax
       \narkistamfamily\Huge\bfseries\textcolor{DGray}{\@title}
       \par
       \vskip 20\p@
     \fi
     \huge\bfseries\textcolor{DGray}{\partname\ \thepart}\par \textcolor{DGray}{יחידות}\par}%
  \vspace*{\fill}
\clearpage\thispagestyle{empty}%\input{copyright}
\newpage
}

% Chapter title
\def\@makechapterhead#1{%
\vspace*{1cm}%
  {\noindent\normalfont
      \narkistamfamily\huge\bfseries\textcolor{DGray}{\chaptername\ \thechapter} % < the only change
        \par\nobreak
        \vskip -10\p@
    \interlinepenalty10000
    #1\par\nobreak
    \vskip30pt
  }}
 
% Starred chapter title
\def\@makeschapterhead#1{%
  \nointerlineskip % To make schapters and sections be similar in the v direction
  \vspace*{1cm}%
  {\noindent\normalfont
    \interlinepenalty10000
    \narkistamfamily\huge\bfseries#1\par\nobreak % < the only change
    \vskip30pt
  }}
 
% Section title; The only changes are: \narkistam font switch, add a vspace to the toc entry, add a vspace*
\renewcommand\section{%
\addtocontents{toc}{\protect\addvspace{5pt}} % adds a vspace to the toc file before every section
\nointerlineskip %added
\vspace*{2cm} %added
\@startsection {section}{1}{\z@}%
  {0pt} %changed
  {2.3ex plus .2ex}%
  {\normalfont\narkistamfamily\Large\bfseries}}
  
% Subsection title; Similar to section, the only change is the \narkistam font switch
\renewcommand\subsection{\@startsection{subsection}{2}{\z@}%
  {-3.25ex\@plus -1ex \@minus -.2ex}%
  {1.5ex \@plus .2ex}%
  {\normalfont\narkistamfamily\large\bfseries}} % changed

% Make starred section and starred chapter similar; Copied from the parskip package
\patchcmd\@startsection
 {\addvspace\@tempskipa}
 {\advance\@tempskipa-\parskip\addvspace\@tempskipa}
 {}{\typeout{Couldn’t patch \string\@startsection}}

% Right align the sections and subsections titles and change the counter numbers color to gray
\renewcommand{\@seccntformat}[1]{%
\hbox to 45pt{\textcolor{DGray}{\csname the#1\endcsname}\hss}}

% Table of Contens formatting
\renewcommand\tableofcontents{%
\pagestyle{plain}
\markboth{\@title}{תוכן העניינים}
% print the title of tableOfContents. Don't use \chapter* as in book.cls so that no \write\stepcounter{chapter} is inserted
  \nointerlineskip % To make schapters and sections be similar in the v direction
  \vspace*{1cm}%
  {\noindent\normalfont
    \interlinepenalty\@M
    \narkistamfamily\huge\bfseries \contentsname \par\nobreak % < the only change
    \vskip20pt
  }
  \@starttoc{toc}%
}

% Lengths used in foramtting toc entries
\newlength{\tocparskip}      \setlength{\tocparskip}{0pt} % parskip is 0 in toc
\newlength{\tocbaselineskip} \setlength{\tocbaselineskip}{13.8pt} % baseline skip is different that the main text
\newlength{\tocsecskip}      \setlength{\tocsecskip}{10pt} % a new length used to make a larger space between chapeters and between sections

% Redefine the starttoc macro
\def\@starttoc#1{%
  \begingroup
  \setlength{\baselineskip}{\tocbaselineskip} \setlength{\parskip}{\tocparskip} % added
    \makeatletter
    \@input{\jobname.#1}%
    \if@filesw
      \expandafter\newwrite\csname tf@#1\endcsname
      \immediate\openout \csname tf@#1\endcsname \jobname.#1\relax
    \fi
    \@nobreakfalse
  \endgroup %original def ends here
  % Add a \clearpage so the toc is on a separate page from the rest of the document
  \clearpage
 }
 
% chapter in toc. chaptername added; do it with patchcmd
\renewcommand*\l@chapter[2]{%
  \ifnum \c@tocdepth >\m@ne
    \addpenalty{-\@highpenalty}%
    \vskip 0.0em \@plus\p@% changed
    \setlength\@tempdima{1.5em}%
    \begingroup
      \parindent \z@ \rightskip \@pnumwidth
      \parfillskip -\@pnumwidth
      \leavevmode \bfseries
      \advance\leftskip\@tempdima
      \hskip -\leftskip
      \chaptername\ #1\nobreak\hfil
      \nobreak\hb@xt@\@pnumwidth{\hss #2%
                                 \kern-\p@\kern\p@}\par
      \penalty\@highpenalty
    \endgroup
  \fi}

% Chapter in toc, only a small change, do it with pacthcmd
\def\@chapter[#1]#2{%
\addtocontents{toc}{\protect\addvspace{\tocsecskip}} % adds a vspace to the toc file before every chapter
  \ifnum \c@secnumdepth >\m@ne
                       \if@mainmatter
                         \refstepcounter{chapter}%
                         \typeout{\@chapapp\space\thechapter.}%
                         \addcontentsline{toc}{chapter}%
                         {\thechapter:\ #1}% <<  changed
                       \else
                         \addcontentsline{toc}{chapter}{#1}%
                       \fi
                    \else
                      \addcontentsline{toc}{chapter}{#1}%
                    \fi
                    \chaptermark{#1}%
                    \addtocontents{lof}{\protect\addvspace{10\p@}}%
                    \addtocontents{lot}{\protect\addvspace{10\p@}}%
                    \if@twocolumn
                      \@topnewpage[\@makechapterhead{#2}]%
                    \else
                      \@makechapterhead{#2}%
                      \@afterheading
                    \fi}
                    
% Sections and subsections in toc:
\renewcommand\@dotsep{1000} % wide enough so dots are not printed
\newlength\tocindent \setlength\tocindent{3em}
\renewcommand*\l@section{\@dottedtocline{1}{0em}{\tocindent}}
\renewcommand*\l@subsection{\@dottedtocline{2}{\tocindent}{25pt}}
EndPreamble

# General formatting

AddToPreamble
% Redefine \emph{...} to be in boldface
\DeclareTextFontCommand{\emph}{\boldmath\bfseries}

% set paragraph skip to 8pt
\parskip=8pt plus 2pt minus 2pt
% no paragraph indentation
\parindent=0pt
% glue inserted at end of paragraphs
\parfillskip=20pt plus 1fil

% Relax the strict rules of line-breaking and paragraph formatting
\tolerance 9999%
\emergencystretch 3em%
EndPreamble
