#\DeclareLyXModule{OpenU Theorems}
#\DeclareCategory{OpenUniversity}
#DescriptionBegin
#Defines theorem environments in Hebrew, built on amsthm. To be used with babel. Author: Ehud Behar. Updated 2026-August-11
#DescriptionEnd
#Author: Ehud Behar

Format 66
Requires amsthm
# Define Counters
Counter definition
    Within         chapter
End

Counter question
    Within         chapter
End

Counter example
    Within         chapter
End

AddToPreamble
% Create a new counter for thm-like environments, reset every time a new \chapter{...} is started
\newcounter{definition}[chapter]
% thm number is printed before chapter number:
\renewcommand{\thedefinition}{\thechapter.\arabic{definition}}
% Define style for thms. This style is used for defs, thms, lemmas, corollaries, etc.
\newtheoremstyle{thms}
  {0pt}% space above
  {0pt}% space below
  {}% body font
  {0pt}% indent amount
  {\narkistamfamily\bfseries}% head font
  {}% punctuation after head
  {\newline}% space after head
  {\thmname{#1}\ \thmnumber{#2}\ \thmnote{(#3)}}% head spec
% macros for correct vskips between the hrules and the theorem
\newlength\thmrulesep    \setlength\thmrulesep{12pt}
\newlength\thmruleskip   \setlength\thmruleskip{17pt}  % outside the rules
\def\thmframe@open{%
  \par \addvspace{\thmruleskip}%
  \hrule
  \prevdepth\dimexpr\baselineskip-\thmrulesep\relax
  \@topsep\parskip
  \@beginparpenalty\@M}          % the top rule may not be orphaned
\def\thmframe@close{%
  \par
  \@tempskipa\lastskip \vskip-\@tempskipa
  \@tempdima\prevdepth \ifdim\@tempdima<\z@ \@tempdima\z@ \fi
  \kern\dimexpr\thmrulesep-\@tempdima\relax
  \nobreak                       % nor the bottom rule from the last line
  \hrule
  \addvspace{\thmruleskip}}

% based on TeX.SE/a/122025, fix when enumerate or itemize are first after theorem head
\newif\ifthm@startlist
\let\thm@dth@orig\deferred@thm@head
\def\deferred@thm@head#1{\global\thm@startlisttrue\thm@dth@orig{#1}}
\dth@everypar=\expandafter{\the\dth@everypar \global\thm@startlistfalse}
\let\thm@trivlist@orig\@trivlist
\def\@trivlist{%
  \if@inlabel\ifthm@startlist
    \leavevmode\hbox{}\par\nobreak
    \vskip\glueexpr-\baselineskip-\partopsep+0pt\relax
    \hrule height\z@ \prevdepth\z@
    \global\thm@startlistfalse
  \fi\fi
  \thm@trivlist@orig}
% same idea for amsmath displays: they don't go through \@trivlist
\newcommand*{\thm@flush@head@for@display}{%
  \if@inlabel\ifthm@startlist
    \leavevmode  % fires \everypar: the deferred head is typeset now
    \unskip\unpenalty\unskip\unpenalty % remove \hskip\thm@headsep and \nobreak\hfil\break
    %\abovedisplayskip11pt\relax This line doesn't seem to have effect
  \fi\fi}
\@for\thm@tmp:=equation,equation*,align,align*,alignat,alignat*,%
    flalign,flalign*,gather,gather*,multline,multline*\do{%
  \AddToHook{env/\thm@tmp/before}{\thm@flush@head@for@display}}
EndPreamble

Style Definition
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             definition
    ResetArgs             1
    KeepEmpty             1 # allow to leave a paragraph empty
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelType             Static
    LabelCounter          definition
    LabelString           "הגדרה \thedefinition"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             def
    Preamble
% Create a new definition environment 
\theoremstyle{thms}% activate style
\newtheorem{definition@thm}[definition]{הגדרה}
\newenvironment{definition}[1][]%
  {\thmframe@open\begin{definition@thm}[#1]}%
  {\end{definition@thm}\thmframe@close}
    EndPreamble
End

Style Theorem
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             theorem
    LabelString           "משפט \thedefinition"
    RefPrefix             thm
    Preamble
\theoremstyle{thms}% activate style
\newtheorem{theorem@thm}[definition]{משפט}
\newenvironment{theorem}[1][]%
  {\thmframe@open\begin{theorem@thm}[#1]}%
  {\end{theorem@thm}\thmframe@close}
    EndPreamble
End

Style Lemma
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             lemma
    LabelString           "למה \thedefinition"
    RefPrefix             lemma
    Preamble
\theoremstyle{thms}% activate style
\newtheorem{lemma@thm}[definition]{למה}
\newenvironment{lemma}[1][]%
  {\thmframe@open\begin{lemma@thm}[#1]}%
  {\end{lemma@thm}\thmframe@close}
    EndPreamble
End

Style Claim
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             claim
    LabelString           "טענה \thedefinition"
    RefPrefix             claim
    Preamble
\theoremstyle{thms}% activate style
\newtheorem{claim@thm}[definition]{טענה}
\newenvironment{claim}[1][]%
  {\thmframe@open\begin{claim@thm}[#1]}%
  {\end{claim@thm}\thmframe@close}
    EndPreamble
End

Style Corollary
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             corollary
    LabelString           "מסקנה \thedefinition"
    RefPrefix             cor
    Preamble
\theoremstyle{thms}% activate style
\newtheorem{corollary@thm}[definition]{מסקנה}
\newenvironment{corollary}[1][]%
  {\thmframe@open\begin{corollary@thm}[#1]}%
  {\end{corollary@thm}\thmframe@close}
    EndPreamble
End

#Style Remark
#    CopyStyle             Definition
#    DependsOn             Definition
#    LatexName             remark
#    LabelString           "הערה \thedefinition"
#    RefPrefix             rmrk
#    Preamble
#\thmblockshared{remark}{definition}{הערה}
#    EndPreamble
#End
#
Style Proof
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             proof
    LabelString           "הוכחה"
    RefPrefix             prf
    Argument 1
      Mandatory 0
      LabelString    "כותרת חלופית"
      Tooltip        "'כותרת מותאמת אישית במקום 'הוכחה"
      IsTocCaption      1
      Decoration    Conglomerate
      Font
        Series Bold
      EndFont
    EndArgument
    Preamble
\def\qedsymbol{\leavevmode\textcolor{DGray}{$\square$}}
\renewenvironment{proof}[1][הוכחה]%
  {\par
   \pushQED{\qed}%
   \normalfont
   \trivlist                % only so \endtrivlist below has a partner
   \@topsep 6\p@ \@topsepadd \z@
   \deferred@thm@head{\noindent{\narkistamfamily\bfseries #1}\newline}}%
  {\popQED\endtrivlist\@endpefalse}
    EndPreamble
End
#
Style Example
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             example
    LabelType             Above
    LabelCounter          example
    KeepEmpty            1 # allow to leave a paragraph empty
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "דוגמה \theexample ◀"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             exmpl
    Preamble
\newcounter{example}[chapter]
\renewcommand{\theexample}{\thechapter.\arabic{example}}
\def\exampleqedsymbol{\leavevmode\textcolor{DGray}{$\blacktriangleright$}}
\newtheoremstyle{example}{0pt}{0pt}{}{0pt}
  {\narkistamfamily\bfseries}{}{\newline}
  {\textcolor{DGray}{$\blacktriangleleft$}\ \thmname{#1}\ \thmnumber{#2}\ \thmnote{(#3)}}
\theoremstyle{example}%
\newtheorem{example@thm}[example]{דוגמה}%
\newenvironment{example}[1][]%
  {\let\qedsymbol\exampleqedsymbol
   \pushQED{\qed}
   \begin{example@thm}[#1]}%
  {\popQED\end{example@thm}}
    EndPreamble
End

Style Examples
    CopyStyle             Example
    DependsOn             Example
    LatexName             examples
    LabelString           "דוגמאות \theexample ◀"
    RefPrefix             exmpl

    Preamble
\theoremstyle{example}%
\newtheorem{examples@thm}[example]{דוגמאות}%
\newenvironment{examples}[1][]%
  {\let\qedsymbol\exampleqedsymbol
   \pushQED{\qed}
   \begin{examples@thm}[#1]}%
  {\popQED\end{examples@thm}}
    EndPreamble
End

AddToPreamble
\newwrite\solutionwrite
\immediate\openout\solutionwrite=solutionlist.tex
\newwrite\hintwrite
\immediate\openout\hintwrite=hintlist.tex
% Close the output and print the stream inside a chapter
\AtEndDocument{%
  \immediate\closeout\hintwrite
  \immediate\closeout\solutionwrite
  \chapter*{רמזים ופתרונות לשאלות בכרך \thepart}
  \section*{רמזים לשאלות ביחידה \thechapter}
  \input hintlist
  \section*{פתרונות לשאלות ביחידה \thechapter}
  \input solutionlist
}

% macro to guarantee that margin reference is anchored on the baseline of the LAST line of the surrounding environment, no matter how that body ended (hmode or vmode).
\newcommand\@MarginAnchor[1]{%
  \ifhmode
    #1%
  \else
    \@tempskipa\lastskip
    \@tempdima\prevdepth
    \ifdim\@tempdima<\z@ \@tempdima\z@ \fi % guard against \prevdepth = -1000pt
    \vskip-\@tempskipa
    \kern-\@tempdima
    #1%
    \kern\@tempdima
    \vskip\@tempskipa
  \fi}

% macro to typeset a single marginpar (used in `question` and `answer` envs)
\protected\def\SingleMarginRef#1{%
  \@MarginAnchor{\marginpar{%
    \setbox\z@\vbox{%
      \hbox{%
        \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
          {\vrule height 5.92mm width\marginparwidth depth 3.5mm}%
          \pdfextension literal direct {0 g}}%
        \hskip4pt #1}%
    }%
    \vskip-\ht\z@\relax
    \box\z@}}%
}

% macro to typeset two marginpars (used in `questionremez` and `hint` envs)
\protected\def\DoubleMarginRefs#1#2{%
  \@MarginAnchor{\marginpar{%
    \setbox\z@\vbox{%
      \hbox{%
        \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
          {\vrule height 3.83mm width\marginparwidth depth 1.76mm}%
          \pdfextension literal direct {0 g}}%
        \hskip4pt #1}%
      \vskip1.55mm
      \hbox{%
        \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
          {\vrule height 3.83mm width\marginparwidth depth 1.76mm}%
          \pdfextension literal direct {0 g}}%
        \hskip4pt #2}%
    }%
    \vskip-\ht\z@\relax
    \box\z@}}%
}
EndPreamble

Style Question
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             question
    LabelType             Static
    LabelCounter          question
    RefPrefix             questn
    KeepEmpty            1 # allow to leave a paragraph empty
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "שאלה \thequestion"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    Preamble
\newcounter{question}[chapter]
\renewcommand{\thequestion}{\thechapter.\arabic{question}}
\theoremstyle{thms}
\newtheorem{question@thm}[question]{שאלה}
\newenvironment{question}[1][]
  {\gdef\exerciseopt{#1}\begin{question@thm}[#1]\label{ques:\thequestion}}
  {\end{question@thm}%
   \SingleMarginRef{הפתרון בעמוד \pageref{sol:\thequestion}}}
    EndPreamble
End

Style Solution
    CopyStyle             Question
    DependsOn             Question
    LatexName             solution
    LabelCounter          ""
    LabelString           "פתרון \thequestion"
    RefPrefix             solutn
    Preamble
\newcounter{solutionaux}
\def\thesolutionaux{\solutionaux@num}
\theoremstyle{thms}
\newtheorem{solutionaux@thm}[solutionaux]{תשובה}
\newenvironment{solutionaux}[2][]{%
  \gdef\solutionaux@num{#2}%
  \begin{solutionaux@thm}[#1]%
  \label{sol:#2}%
}{%
  \end{solutionaux@thm}%
  \SingleMarginRef{השאלה בעמוד \pageref{ques:\solutionaux@num}}%
  \par\ignorespacesafterend
}

\NewDocumentEnvironment{solution}{+b}{%
  \immediate\write\solutionwrite{^^J%
    \detokenize{\begin{solutionaux}}[\exerciseopt]\string{\thequestion\string}^^J%
    \detokenize{#1}^^J%
    \detokenize{\end{solutionaux}}%
  }%
}{\immediate\write\solutionwrite{\noexpand\vspace{\parskip}}}
    EndPreamble
End



Style QuestionW/Hint
    CopyStyle             Question
    DependsOn             Question
    LatexName             questionremez
    LabelString           "שאלה (עם רמז) \thequestion"
    RefPrefix             questn
    Preamble
\theoremstyle{thms}
\newtheorem{questionremez@thm}[question]{שאלה}
\newenvironment{questionremez}[1][]
  {\gdef\exerciseopt{#1}\begin{questionremez@thm}[#1]\label{ques:\thequestion}}
  {\end{questionremez@thm}%
  \DoubleMarginRefs{רמז בעמוד \pageref{hint:\thequestion}}{התשובה בעמוד \pageref{sol:\thequestion}}}
    EndPreamble
End

Style Hint
    CopyStyle             Question
    DependsOn             Question
    LatexName             hint
    LabelCounter          ""
    LabelString           "רמז \thequestion"
    RefPrefix             hint
    Preamble
\newcounter{hintaux}
\def\thehintaux{\hintaux@num}
\theoremstyle{thms}
\newtheorem{hintaux@thm}[hintaux]{רמז}
\newenvironment{hintaux}[2][]{%
  \gdef\hintaux@num{#2}%
  \begin{hintaux@thm}[#1]%
  \label{hint:#2}%
}{%
  \end{hintaux@thm}%
  \DoubleMarginRefs{השאלה בעמוד \pageref{ques:\hintaux@num}}{התשובה בעמוד \pageref{sol:\hintaux@num}}%
  \par\ignorespacesafterend
}

\NewDocumentEnvironment{hint}{+b}{%
  \immediate\write\hintwrite{^^J%
    \detokenize{\begin{hintaux}}[\exerciseopt]\string{\thequestion\string}^^J%
    \detokenize{#1}^^J%
    \detokenize{\end{hintaux}}%
  }%
}{\immediate\write\hintwrite{\noexpand\vspace{\parskip}}}
    EndPreamble
End