#\DeclareLyXModule{OpenU Theorems}
#\DeclareCategory{OpenUniversity}
#DescriptionBegin
#Defines theorem environments in Hebrew. To be used with babel. Author: Ehud Behar. Updated 2026-May-18
#DescriptionEnd
#Author: Ehud Behar

Format 66
Provides amsthm 1 # Prevent autoloading of amsthm package
# Define Counters
Counter definition
    Within         chapter
End

Counter question
    Within         chapter
End

Counter example
    Within         chapter
End

AddToPreamble
EndPreamble

Style Definition
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             definition
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelType             Static
    LabelCounter          definition
    LabelString           "הגדרה \thedefinition"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             def
    Preamble
% Create a new counter for thm-like environments, reset every time a new \chapter{...} is started
\newcounter{definition}[chapter]
% thm number is printed before chapter number:
\renewcommand{\thedefinition}{\thechapter.\arabic{definition}}
% shared thm-like environment:
\newcommand{\thmblockshared}[3]{%
  \newenvironment{#1}[1][]%
  {%
    \refstepcounter{#2}%
    \vskip8pt%
    \par\hrule\vskip8pt%
    \noindent{\bfseries\narkistamfamily#3\ }\csname the#2\endcsname%
    \if\relax\detokenize{##1}\relax\else(\bfseries\narkistamfamily\ ##1)\fi%
    \par%
  }%
  {%
    \nobreak\par\vskip8pt\hrule\vskip8pt%
  }%
}

% Create a new definition environment 
\thmblockshared{definition}{definition}{הגדרה}
    EndPreamble
End

Style Theorem
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             theorem
    LabelString           "משפט \thedefinition"
    RefPrefix             thm
    Preamble
\thmblockshared{theorem}{definition}{משפט}
    EndPreamble
End

Style Lemma
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             lemma
    LabelString           "למה \thedefinition"
    RefPrefix             lemma
    Preamble
\thmblockshared{lemma}{definition}{למה}
    EndPreamble
End

Style Claim
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             claim
    LabelString           "טענה \thedefinition"
    RefPrefix             claim
    Preamble
\thmblockshared{claim}{definition}{טענה}
    EndPreamble
End

Style Corollary
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             corollary
    LabelString           "מסקנה \thedefinition"
    RefPrefix             cor
    Preamble
\thmblockshared{corollary}{definition}{מסקנה}
    EndPreamble
End

#Style Remark
#    CopyStyle             Definition
#    DependsOn             Definition
#    LatexName             remark
#    LabelString           "הערה \thedefinition"
#    RefPrefix             rmrk
#    Preamble
#\thmblockshared{remark}{definition}{הערה}
#    EndPreamble
#End

Style Proof
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             proof
    LabelString           "הוכחה"
    RefPrefix             prf
    Preamble
\newenvironment{proof}[1][]%
  {%
    \vskip6pt%
    \noindent{\bfseries\narkistamfamily הוכחה}%
    \if\relax\detokenize{#1}\relax\else\ (#1)\fi%
    \par%
  }%
  {%
    \par\ignorespacesafterend
  }%
    EndPreamble
End

Style Example
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             example
    LabelType             Above
    LabelCounter          example
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "◀ דוגמה \theexample"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             exmpl
    Preamble
\newcounter{example}[chapter]
\newenvironment{example}[1][]%
  {%
    \refstepcounter{example}%
    \vskip6pt%
    \noindent\textcolor{DGray}{$\blacktriangleleft$}\ {\bfseries\narkistamfamily דוגמה \theexample}%
    \if\relax\detokenize{#1}\relax\else{\bfseries\narkistamfamily:\ #1}\fi%
    \par%
  }%
  {%
    \par\ignorespacesafterend
  }%
    EndPreamble
End

Style Examples
    CopyStyle             Example
    DependsOn             Example
    LatexName             examples
    LabelString           "◀ דוגמאות \theexample"
    RefPrefix             exmpl

    Preamble
\newenvironment{examples}[1][]%
  {%
    \refstepcounter{example}%
    \vskip6pt%
    \noindent\textcolor{DGray}{$\blacktriangleleft$}\ {\bfseries\narkistamfamily דוגמאות \theexample}%
    \if\relax\detokenize{#1}\relax\else{\bfseries\narkistamfamily:\ #1}\fi%
    \par%
  }%
  {%
    \par\ignorespacesafterend
  }%
    EndPreamble
End

Style Question
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             question
    LabelType             Above
    LabelCounter          question
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "שאלה \thequestion"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             questn
    Preamble
\newcounter{question}[chapter]
\newenvironment{question}[1][]%
  {%
    \refstepcounter{question}%
    \vskip6pt%
    \noindent{\bfseries\narkistamfamily שאלה \thequestion}%
    \if\relax\detokenize{#1}\relax\else{\bfseries\narkistamfamily:\ #1}\fi%
    \par%
  }%
  {%
    \par\ignorespacesafterend
  }%
    EndPreamble
End

Style Solution
    CopyStyle             Example
    DependsOn             Example
    LatexName             solution
    LabelCounter          question
    LabelString           "פתרון \thequestion"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             solutn
    Preamble
\newenvironment{solution}[1][]%
  {%
    \vskip6pt%
    \noindent{\bfseries\narkistamfamily פתרון \thequestion}%
    \if\relax\detokenize{#1}\relax\else{\bfseries\narkistamfamily:\ #1}\fi%
    \par%
  }%
  {%
    \par\ignorespacesafterend
  }%
    EndPreamble
End
