#\DeclareLyXModule{OpenU Formatting}
#DescriptionBegin
#Includes commands and settings for the document layout. Author: Ehud Behar. Updated 2026-Feb-11
#DescriptionEnd
#Author: Ehud Behar

Format 66

Requires xcolor,amssymb,enumitem,graphicx

ClassOptions
  Other "fleqn,leqno,provide=*,bidi=default,openany"
End

# Choose the engine that will process the .tex file when opened in TeXShop, TeXWorks or TeXstudio
AddToPreamble
% !TEX TS-program = lualatex
EndPreamble

AddToPreamble
\definecolor{DGray}{RGB}{149,149,149} % Dark Gray
\definecolor{LGray}{RGB}{216,216,216} % Light Gray
\definecolor{VDGray}{RGB}{110,110,110} % VeryDarkGray
EndPreamble

# Defone font sizes
AddToPreamble
% Define normal size to be 11.5pt
\def\normalsize{%
  \@setfontsize\normalsize{11.5}{17pt}%
  \abovedisplayskip 11.5pt plus 2.3pt minus 6.9pt
  \abovedisplayshortskip 0.0pt plus 3.45pt
  \belowdisplayskip 11.5pt plus 2.3pt minus 6.9pt
  \belowdisplayshortskip 6.9pt plus 3.45pt minus 3.45pt
  \let\@listi\@listI
}%
% Define small size to be 9.5pt
\def\small{%
  \@setfontsize\small{9.5}{14.04pt}%
  \abovedisplayskip 9.5pt plus 1.9pt minus 5.7pt
  \abovedisplayshortskip 0.0pt plus 2.85pt
  \belowdisplayskip 9.5pt plus 1.9pt minus 5.7pt
  \belowdisplayshortskip 5.7pt plus 2.85pt minus 2.85pt
  \def\@listi{%
    \leftmargin\leftmargini
    \topsep4.16391pt plus 2.08261pt minus 2.08261pt
    \parsep2.08261pt plus 1.04063pt minus 1.04063pt
    \itemsep\parsep
  }%
}%
% Define smallr font size; the 'r' stands for "reduced" or "relative". This font size is used only in the headers
\def\smallr{\@setfontsize\smallr{10pt}{14.782pt}}%
\def\Huge{\@setfontsize\Huge{30pt}{36pt}}%
\def\huge{\@setfontsize\huge{26.0975pt}{31.317pt}}%
\def\Large{\@setfontsize\Large{20.075pt}{22.0pt}}%
\def\large{\@setfontsize\large{17.063pt}{18.0pt}}%
EndPreamble

# fontspec and babel commands to select fonts
AddToPreamble
% Load fontspec package
\usepackage{fontspec}
\defaultfontfeatures{Scale=MatchUppercase, Ligatures=TeX}
% Glyph em-dash is not available in NarkisimMF, print it en-dash:
\catcode`—=\active \protected\def—{\char`\--}
% Use unicode-math package, so math fonts scales to 11.5pt font size
\usepackage[mathbf=sym]{unicode-math}
\setmathfont{Latin Modern Math} %to do: change this to cambria
% Make emphasized math also in bold:
\setmathfont{Latin Modern Math}[version=bold,FakeBold=3]
% Use Latin Modern Math for blackboard
\let\mathbb\relax
\DeclareMathAlphabet{\mathbb}{U}{msb}{m}{n}%

% add babel font commands to end of preamble
\usepackage{etoolbox}
\AtEndPreamble{%
\babelfont[english]{rm}
    [Script=Latin,
     SizeFeatures={
         {Size={10-},Scale=0.86956},
         {Size={9-10},Scale=0.894736},
         {Size={8-9},Scale=1},
         {Size={-8}}
     },
     BoldFeatures={
         SizeFeatures={
             {Size={10-},Scale=0.86956},
             {Size={9-10},Scale=0.894736},
             {Size={8-9},Scale=1},
             {Size={-8}}
         }
     }]
    {Times New Roman}
% Main Hebrew font (rm family)
\babelfont[hebrew]{rm}[Script=Hebrew]{NarkisimMF}%
% Monospace Hebrew font (teletype, tt family)
\babelfont[hebrew]{tt}[Script=Hebrew]{Courier New}
% Sans serif Hebrew font (sf family)
\babelfont[hebrew]{sf}[Script=Hebrew]{Open Sans Hebrew}
% NarkisTamMF is used in the headers
\babelfont[hebrew]{narkistam}[Script=Hebrew,BoldFont=NarkisTamMF]{NarkisTamMF}
\setlocalecaption{hebrew}{part}{כרך}
\setlocalecaption{hebrew}{chapter}{יחידה}
\setlocalecaption{hebrew}{contents}{תוכן עניינים ל\partname\ \thepart}
\renewcommand{\thepage}{\textdir TLT\csname @arabic\endcsname \c@page} %Reverse direction of page numbers
}

% Define a new length `\headwidth` that is a total width of the headers:
\newlength\headwidth \headwidth=\dimexpr\textwidth+\marginparsep+\marginparwidth

% Redefine the plain page style (used on chapter opening pages)
\renewcommand{\ps@plain}{%
  \renewcommand{\@oddhead}{\hbox{\vbox{\hsize=\headwidth \hfill{\narkistamfamily\large\thepage}\vskip2mm\hrule}}}
  \renewcommand{\@evenhead}{\hfill\thepage}%
  \renewcommand{\@oddfoot}{}%
  \renewcommand{\@evenfoot}{}%
}

% Redefine the headings page style (used on regular pages)
\renewcommand{\ps@headings}{%
  \renewcommand{\@oddhead}{\hbox{\vbox{\hsize=\headwidth \hfill{\narkistamfamily\rightmark\hskip2mm\large\thepage}\vskip1mm\hrule}}}
  \renewcommand{\@evenhead}{\hbox{\vbox{\hsize=\headwidth \narkistamfamily{\large\thepage}~\leftmark\vskip1mm\hrule}}}
}

% Customize chapter and section marks
\renewcommand{\chaptermark}[1]{%
  \markboth{\chaptername~\thechapter\hskip0.2cm #1}{}%
}
\renewcommand{\sectionmark}[1]{%
  \markright{{\textdir TLT\thesection}~#1}%
}
\pagestyle{headings}

% main matter page layout
\pagewidth=210mm \paperwidth=\pagewidth
\pageheight=297mm \paperheight=\pageheight
\textwidth=125mm
\textheight=220mm
\marginparsep=7mm
\marginparwidth=43mm
\evensidemargin=0cm
\headheight=22pt
\topmargin=0mm
\headsep=10mm
% apply a twosided layout in which margins are not swapped on alternate pages:
\oddsidemargin=\evensidemargin
\@twocolumnfalse
\@twosidetrue
% and marginal notes stay always on the same side:
\@mparswitchfalse
\@reversemarginfalse
EndPreamble

# General formatting

AddToPreamble
% Redefine \emph{...} to be in boldface
\DeclareTextFontCommand{\emph}{\boldmath\bfseries}

% set paragraph skip to 8pt
\parskip=8pt plus 2pt minus 2pt
% no paragraph indentation
\parindent=0pt
% glue inserted at end of paragraphs
\parfillskip=20pt plus 1fil

% Relax the strict rules of line-breaking and paragraph formatting
\tolerance 9999%
\emergencystretch 3em%
EndPreamble
