#\DeclareLyXModule{OpenU Theorems}
#\DeclareCategory{OpenUniversity}
#DescriptionBegin
#Defines theorem environments in Hebrew. To be used with babel. Author: Ehud Behar. Updated 2026-July-3
#DescriptionEnd
#Author: Ehud Behar

Format 66
Requires amsthm
# Define Counters
Counter definition
    Within         chapter
End

Counter question
    Within         chapter
End

Counter example
    Within         chapter
End

AddToPreamble
EndPreamble

Style Definition
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             definition
    ResetArgs             1
    KeepEmpty             1 # allow to leave a paragraph empty
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelType             Static
    LabelCounter          definition
    LabelString           "הגדרה \thedefinition"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             def
    Preamble
% Create a new counter for thm-like environments, reset every time a new \chapter{...} is started
\newcounter{definition}[chapter]
% thm number is printed before chapter number:
\renewcommand{\thedefinition}{\thechapter.\arabic{definition}}
% shared thm-like environment:
\newcommand{\thmblockshared}[3]{%
  \newenvironment{#1}[1][]%
  {%
    \refstepcounter{#2}%
\vskip\dimexpr\baselineskip
\par
\hrule
\vskip\dimexpr\parskip/2
    \noindent{\narkistamfamily\bfseries#3\ \csname the#2\endcsname}%
    \if\relax\detokenize{##1}\relax\else{\narkistamfamily\bfseries\ (##1)}\fi%
    \newline%
  }%
  {%
    \nobreak\par
    \vskip\dimexpr\baselineskip
    \hrule
    \vskip\dimexpr\parskip/2
    \par%
  }%
}

% Create a new definition environment 
\thmblockshared{definition}{definition}{הגדרה}
    EndPreamble
End

Style Theorem
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             theorem
    LabelString           "משפט \thedefinition"
    RefPrefix             thm
    Preamble
\thmblockshared{theorem}{definition}{משפט}
    EndPreamble
End

Style Lemma
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             lemma
    LabelString           "למה \thedefinition"
    RefPrefix             lemma
    Preamble
\thmblockshared{lemma}{definition}{למה}
    EndPreamble
End

Style Claim
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             claim
    LabelString           "טענה \thedefinition"
    RefPrefix             claim
    Preamble
\thmblockshared{claim}{definition}{טענה}
    EndPreamble
End

Style Corollary
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             corollary
    LabelString           "מסקנה \thedefinition"
    RefPrefix             cor
    Preamble
\thmblockshared{corollary}{definition}{מסקנה}
    EndPreamble
End

#Style Remark
#    CopyStyle             Definition
#    DependsOn             Definition
#    LatexName             remark
#    LabelString           "הערה \thedefinition"
#    RefPrefix             rmrk
#    Preamble
#\thmblockshared{remark}{definition}{הערה}
#    EndPreamble
#End

Style Proof
    CopyStyle             Definition
    DependsOn             Definition
    LatexName             proof
    LabelString           "הוכחה"
    RefPrefix             prf
    Preamble
\def\qedsymbol{\leavevmode\textcolor{DGray}{$\square$}}
\renewenvironment{proof}[1][]%
  {%
    \par\vskip6pt%
    \pushQED{\qed}%
    \topsep0pt\partopsep0pt\relax
    \trivlist
    \item[\hskip\labelsep
      {\narkistamfamily\bfseries הוכחה%
       \if\relax\detokenize{#1}\relax\else\ (#1)\fi}]%
    \hfil\break\ignorespaces
  }%
  {%
    \popQED\endtrivlist\@endpefalse
  }%
    EndPreamble
End

Style Example
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             example
    LabelType             Above
    LabelCounter          example
    Keep Empty            1 # allow to leave a paragraph empty
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "דוגמה \theexample ◀"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    RefPrefix             exmpl
    Preamble
\newcounter{example}[chapter]
\renewcommand{\theexample}{\thechapter.\arabic{example}}
\def\exampleqedsymbol{\leavevmode\textcolor{DGray}{$\blacktriangleright$}}
\newenvironment{example}[1][]%
  {%
    \refstepcounter{example}
    \par\vskip6pt%
    \let\qedsymbol\exampleqedsymbol % local; reverts after \end{example}
    \pushQED{\qed}%
    \topsep0pt\partopsep0pt\relax
    \trivlist
    \item[\hskip\labelsep
      \textcolor{DGray}{$\blacktriangleleft$}~{\narkistamfamily\bfseries דוגמה \theexample%
       \if\relax\detokenize{#1}\relax\else\ (#1)\fi}]%
    \hfil\break\ignorespaces
  }%
  {%
    \popQED\endtrivlist\@endpefalse
  }%
    EndPreamble
End


Style Examples
    CopyStyle             Example
    DependsOn             Example
    LatexName             examples
    LabelString           "דוגמאות \theexample ◀"
    RefPrefix             exmpl

    Preamble
\newenvironment{examples}[1][]%
  {%
    \refstepcounter{example}
    \par\vskip6pt%
    \let\qedsymbol\exampleqedsymbol % local; reverts after \end{example}
    \pushQED{\qed}%
    \topsep0pt\partopsep0pt\relax
    \trivlist
    \item[\hskip\labelsep
      \textcolor{DGray}{$\blacktriangleleft$}~{\narkistamfamily\bfseries דוגמאות \theexample%
       \if\relax\detokenize{#1}\relax\else\ (#1)\fi}]%
    \hfil\break\ignorespaces
  }%
  {%
    \popQED\endtrivlist\@endpefalse
  }%
    EndPreamble
End

AddToPreamble
\newwrite\solutionwrite
\immediate\openout\solutionwrite=solutionlist.tex
\newwrite\hintwrite
\immediate\openout\hintwrite=hintlist.tex
% Close the output and print the stream inside a chapter
\AtEndDocument{%
  \immediate\closeout\hintwrite
  \immediate\closeout\solutionwrite
  \chapter*{רמזים ופתרונות לשאלות בכרך \thepart}
  \section*{רמזים לשאלות ביחידה \thechapter}
  \input hintlist
  \section*{פתרונות לשאלות ביחידה \thechapter}
  \input solutionlist
}

% macro to typeset a single marginpar (used in `question` and `answer` envs)
\protected\def\SingleMarginRef#1{%
\marginpar{%
\vskip-8pt %controls vertical placement
  \hbox{%
    \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
    {\vrule height 5.92mm width\marginparwidth depth 3.5mm}
    \pdfextension literal direct {0 g}}%
    \hskip4pt #1} % 4pt gap from right edge
  }%
}

% macro to typeset two marginpars (used in `questionremez` and `hint` envs)
\protected\def\DoubleMarginRefs#1#2{%
\marginpar{%
\vskip-8pt %controls vertical placement
  \hbox{%
    \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
      {\vrule height 3.83mm width\marginparwidth depth 1.76mm}%
      \pdfextension literal direct {0 g}}%
    \hskip4pt #1}
  \vskip1.55mm % controls vertical distance between the two gray rectangles
  \hbox{%
    \rlap{\pdfextension literal direct {0.847 0.847 0.847 rg}%
      {\vrule height 3.83mm width\marginparwidth depth 1.76mm}%
      \pdfextension literal direct {0 g}}%
    \hskip4pt #2}%
}%
}
EndPreamble

Style Question
    Category              Reasoning
    Margin                Dynamic
    LatexType             Environment
    LatexName             question
    LabelType             Static
    LabelCounter          question
    RefPrefix             questn
    Keep Empty            1 # allow to leave a paragraph empty
    ResetArgs             1
    Argument              1
            LabelString    "Additional Theorem Text"
            Tooltip        "Additional text appended to the theorem header"
            IsTocCaption      1
         Decoration    Minimalistic
        EndArgument
    AddToToc              "משפטים והגדרות"
    IsTocCaption          1
    LabelSep              xx
    TopSep                1
    BottomSep             1
    LabelString           "שאלה \thequestion"
    LabelFont
      Shape               Up
      Series              Bold
    EndFont
    Preamble
\newcounter{question}[chapter]
\renewcommand{\thequestion}{\thechapter.\arabic{question}}
\newenvironment{question}[1][]{%
  \gdef\exerciseopt{#1}%
  \refstepcounter{question}%
  \par\vspace{\parskip}%
  \noindent{\narkistamfamily\bfseries שאלה \thequestion}%
  \if\relax\detokenize{#1}\relax\else~{\narkistamfamily\bfseries(#1)}\fi%
  \par%
  \SingleMarginRef{הפתרון בעמוד \pageref{sol:\thequestion}}
  }%
  {%
  \label{ques:\thequestion}
\par\ignorespacesafterend
  }%
    EndPreamble
End

Style Solution
    CopyStyle             Question
    DependsOn             Question
    LatexName             solution
    LabelCounter          ""
    LabelString           "פתרון \thequestion"
    RefPrefix             solutn
    Preamble
\newenvironment{solutionaux}[2][]{%
  \par\noindent{\normalfont\bfseries תשובה #2}%
  \if\relax\detokenize{#1}\relax\else~{\bfseries(#1)}\fi%
  \par
}
{%
\par\ignorespacesafterend
}

\NewDocumentEnvironment{solution}{+b}{
  \immediate\write\solutionwrite{^^J%
    \detokenize{\begin{solutionaux}}[\exerciseopt]^^J
    \string{\thequestion\string}^^J%
    \noexpand\label{sol:\thequestion}^^J%
    \noexpand\SingleMarginRef{השאלה בעמוד \noexpand\pageref{ques:\thequestion}}^^J%
    \detokenize{#1}^^J%
    \detokenize{\end{solutionaux}}
  }%
}{%
\immediate\write\solutionwrite{\noexpand\vspace{\parskip}}
}
    EndPreamble
End



Style QuestionW/Hint
    CopyStyle             Question
    DependsOn             Question
    LatexName             questionremez
    LabelString           "שאלה (עם רמז) \thequestion"
    RefPrefix             questn
    Preamble
\newenvironment{questionremez}[1][]{%
  \gdef\exerciseopt{#1}%
  \refstepcounter{question}%
  \par\vspace{\parskip}%
  \noindent{\narkistamfamily\bfseries שאלה \thequestion}%
  \if\relax\detokenize{#1}\relax\else~{\narkistamfamily\bfseries(#1)}\fi%
  \par%
\DoubleMarginRefs{רמז בעמוד \pageref{hint:\thequestion}}{התשובה בעמוד \pageref{sol:\thequestion}}
}%
{%
  \label{ques:\thequestion}
  \par\ignorespacesafterend
}%
    EndPreamble
End

Style Hint
    CopyStyle             Question
    DependsOn             Question
    LatexName             hint
    LabelCounter          ""
    LabelString           "רמז \thequestion"
    RefPrefix             hint
    Preamble
\newenvironment{hintaux}[2][]{%
  \par\noindent{\normalfont\bfseries רמז #2}%
  \if\relax\detokenize{#1}\relax\else~{\bfseries(#1)}\fi%
  \par
}
{%
\par\ignorespacesafterend
}

\NewDocumentEnvironment{hint}{+b}{
  \immediate\write\hintwrite{^^J%
    \detokenize{\begin{hintaux}}[\exerciseopt]^^J
    \string{\thequestion\string}^^J%
    \noexpand\label{hint:\thequestion}^^J%
    {\DoubleMarginRefs{השאלה בעמוד \pageref{ques:\thequestion}}{התשובה בעמוד \pageref{sol:\thequestion}}}
    \detokenize{#1}^^J%
^^J%
    \detokenize{\end{hintaux}}
  }%
}{%
\immediate\write\hintwrite{\noexpand\vspace{\parskip}}
}
    EndPreamble
End